name:                moxfield-to-forge
version:             0.1.0.0
github:              "andreamanfroi/moxfield-to-forge"
license:             BSD-3-Clause
author:              "andreamanfroi"
maintainer:          "andrea.manfroi@"
copyright:           "none"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            parsers, fun, magic-the-gathering

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andreamanfroi/moxfield-to-forge#readme>

dependencies:
- base >= 4.7 && < 5
- text
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  moxfield-to-forge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moxfield-to-forge

tests:
  moxfield-to-forge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moxfield-to-forge
